# Recommendations based on Jaccard index
In this Notebook you will write the function that can be implemented in the Streamlit app. The actual code is already implemented in the streamlit app if you want to be inspired.

### 1. Loading the data
Load a subset from the ratings dataset.

In [2]:
import pandas as pd
df = pd.read_csv('./data/BX-Book-Ratings-Subset.csv', sep=';', encoding='latin-1')

### 2. Generating the recommendations

In [3]:
import itertools

# user we want to check
id = 98783

def get_jaccard_recommendations(id, threshold=0.8):
  # create lists per user
    users = df.groupby('User-ID')['ISBN'].apply(list)
  
    new_content = []
    similar_users = []
    a = set(users.pop(id))

    for user, value in users.items():
        b = set(value)
        jaccard = float(len(a & b) / len(a | b)) # or .intersection() and .union()
        distance = 1 - jaccard

        if distance < threshold:
            new_content.append(b-a)
            similar_users.append(user)

    new_content = list(itertools.chain(*new_content))

    df_recommendations = df[
        df['User-ID'].isin(similar_users) & # why would we need this?
        df['ISBN'].isin(new_content)
    ]

    df_recommendations = df_recommendations.sort_values('Book-Rating', ascending=False)

    return df_recommendations

get_jaccard_recommendations(id, 0.8)

       User-ID        ISBN  Book-Rating
29650   199515  0451176464           10
29642   199515  0345427637           10
29644   199515  0440343194           10
39054   261998  0345384466           10
29641   199515  0345409973            9
39061   261998  0345423402            9
29648   199515  0451166892            9
39062   261998  0345434803            9
29649   199515  0451172817            8
39058   261998  0345404319            8
39049   261998  0156711427            8
29647   199515  0446610038            8
39060   261998  0345422384            8
29646   199515  0446608815            8
29645   199515  0446606189            8
29643   199515  0425155404            8
39059   261998  0345409671            8
39063   261998  0380820854            7
29640   199515  0345404319            7
39056   261998  0345387651            5
29634   199515  0061097853            5